export const options = {
  serviceType: [
    { label: 'Delivery',
      value: 'delivery',
    },
    { label: 'Pickup',
      value: 'pickup',
    },
    { label: 'Dine-in',
      value: 'dine-in',
    },
    { label: 'All',
      value: 'all',
    },
  ],
  dietary: [
    { label: 'Kosher',
      value: 'kosher',
    },
    { label: 'Halal',
      value: 'halal',
    },
    { label: 'Vegan',
      value: 'vegan',
    },
    { label: 'Vegetarian',
      value: 'vegetarian',
    },
    { label: 'Gluten-free',
      value: 'gluten-free',
    },
    { label: 'Lactose-free',
      value: 'lactose-free',
    },
  ]
};